project_name: ksops-dry-run

builds:
  - id: ksops-dry-run
    binary: ksops-dry-run

    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64

    flags:
      - -buildvcs=false
      - -trimpath

    ldflags:
      - -s -w
      - -buildid=
      - -X main.version={{ .Tag }}

    env:
      - CGO_ENABLED=0

archives:
  - id: ksops-dry-run
    builds: [ksops-dry-run]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  name_template: "{{ .Tag }} Release"
  prerelease: auto

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true
